In [1]:
#Source : https://www.kaggle.com/faressayah/ensemble-ml-algorithms-bagging-boosting-voting

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")

In [2]:
# dataset
df = pd.read_csv("./input/divorce.csv")
display(df)

Sorry_end  Ignore_diff  begin_correct  Contact  Special_time  \
0            2            2              4        1             0   
1            4            4              4        4             4   
2            2            2              2        2             1   
3            3            2              3        2             3   
4            2            2              1        1             1   
..         ...          ...            ...      ...           ...   
165          0            0              0        0             0   
166          0            0              0        0             0   
167          1            1              0        0             0   
168          0            0              0        0             0   
169          0            0              0        0             0   

     No_home_time  2_strangers  enjoy_holiday  enjoy_travel  common_goals  \
0               0            0              0             0             0   
1               0            0              4             4             4   
2               3            2              1             1             2   
3               3            3              3             3             3   
4               1            0              0             0             0   
..            ...          ...            ...           ...           ...   
165             0            0              0             0             0   
166             0            0              0             0             0   
167             0            0              0             0             1   
168             0            0              0             0             0   
169             0            0              1             0             0   

     ...  silence_for_harm  silence_fear_anger  I'm_right  accusations  \
0    ...                 2                   1          3            3   
1    ...                 2                   2          3            4   
2    ...                 3                   2          3            1   
3    ...                 2                   2          3            3   
4    ...                 2                   1          2            3   
..   ...               ...                 ...        ...          ...   
165  ...                 1                   0          4            1   
166  ...                 4                   1          2            2   
167  ...                 3                   0          2            0   
168  ...                 3                   3          2            2   
169  ...                 3                   4          4            0   

     I'm_not_guilty  I'm_not_wrong  no_hesitancy_inadequate  \
0                 3              2                        3   
1                 4              4                        4   
2                 1              1                        2   
3                 3              3                        2   
4                 2              2                        2   
..              ...            ...                      ...   
165               1              4                        2   
166               2              2                        3   
167               1              1                        3   
168               3              2                        4   
169               1              3                        3   

     you're_inadequate  incompetence  Divorce_Y_N  
0                    2             1            1  
1                    2             2            1  
2                    2             2            1  
3                    2             2            1  
4                    1             0            1  
..                 ...           ...          ...  
165                  2             2            0  
166                  2             2            0  
167                  0             0            0  
168                  3             1            0  
169                  3           

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 55 columns):
Sorry_end                        170 non-null int64
Ignore_diff                      170 non-null int64
begin_correct                    170 non-null int64
Contact                          170 non-null int64
Special_time                     170 non-null int64
No_home_time                     170 non-null int64
2_strangers                      170 non-null int64
enjoy_holiday                    170 non-null int64
enjoy_travel                     170 non-null int64
common_goals                     170 non-null int64
harmony                          170 non-null int64
freeom_value                     170 non-null int64
entertain                        170 non-null int64
people_goals                     170 non-null int64
dreams                           170 non-null int64
love                             170 non-null int64
happy                            170 non-null int64
marriage   

In [4]:
df.isnull().sum()

Sorry_end                        0
Ignore_diff                      0
begin_correct                    0
Contact                          0
Special_time                     0
No_home_time                     0
2_strangers                      0
enjoy_holiday                    0
enjoy_travel                     0
common_goals                     0
harmony                          0
freeom_value                     0
entertain                        0
people_goals                     0
dreams                           0
love                             0
happy                            0
marriage                         0
roles                            0
trust                            0
likes                            0
care_sick                        0
fav_food                         0
stresses                         0
inner_world                      0
anxieties                        0
current_stress                   0
hopes_wishes                     0
know_well           

In [5]:
pd.set_option('display.float_format', '{:.2f}'.format)
df.describe()

Sorry_end  Ignore_diff  begin_correct  Contact  Special_time  \
count     170.00       170.00         170.00   170.00        170.00   
mean        1.78         1.65           1.76     1.48          1.54   
std         1.63         1.47           1.42     1.50          1.63   
min         0.00         0.00           0.00     0.00          0.00   
25%         0.00         0.00           0.00     0.00          0.00   
50%         2.00         2.00           2.00     1.00          1.00   
75%         3.00         3.00           3.00     3.00          3.00   
max         4.00         4.00           4.00     4.00          4.00   

       No_home_time  2_strangers  enjoy_holiday  enjoy_travel  common_goals  \
count        170.00       170.00         170.00        170.00        170.00   
mean           0.75         0.49           1.45          1.46          1.58   
std            0.90         0.90           1.55          1.56          1.42   
min            0.00         0.00           0.00          0.00          0.00   
25%            0.00         0.00           0.00          0.00          0.00   
50%            0.00         0.00           1.00          1.00          2.00   
75%            1.00         1.00           3.00          3.00          3.00   
max            4.00         4.00           4.00          4.00          4.00   

       ...  silence_for_harm  silence_fear_anger  I'm_right  accusations  \
count  ...            170.00              170.00     170.00       170.00   
mean   ...              2.55                2.27       2.74         2.38   
std    ...              1.37                1.59       1.14         1.51   
min    ...              0.00                0.00       0.00         0.00   
25%    ...              2.00                1.00       2.00         1.00   
50%    ...              3.00                2.00       3.00         3.00   
75%    ...              4.00                4.00       4.00         4.00   
max    ...              4.00                4.00       4.00         4.00   

       I'm_not_guilty  I'm_not_wrong  no_hesitancy_inadequate  \
count          170.00         170.00                   170.00   
mean             2.43           2.48                     2.52   
std              1.41           1.26                     1.48   
min              0.00           0.00                     0.00   
25%              1.00           2.00                     1.00   
50%              2.00           3.00                     3.00   
75%              4.00           4.00                     4.00   
max              4.00           4.00                     4.00   

       you're_inadequate  incompetence  Divorce_Y_N  
count             170.00        170.00       170.00  
mean                2.24          2.01         0.49  
std                 1.51          1.67         0.50  
min                 0.00          0.00         0.00  
25%                 1.00          0.00         0.00  
50%                 2.00          2.00         0.00  
75%                 4.00          4.00         1.00  
max                 4.00          4.00         1.00  

[8 rows x 55 columns]

In [6]:
categorical_val = []
continous_val = []
for column in df.columns:
#     print('==============================')
#     print(f"{column} : {df[column].unique()}")
    if len(df[column].unique()) <= 10:
        categorical_val.append(column)
    else:
        continous_val.append(column)

In [7]:
df.columns

Index(['Sorry_end', 'Ignore_diff', 'begin_correct', 'Contact', 'Special_time',
       'No_home_time', '2_strangers', 'enjoy_holiday', 'enjoy_travel',
       'common_goals', 'harmony', 'freeom_value', 'entertain', 'people_goals',
       'dreams', 'love', 'happy', 'marriage', 'roles', 'trust', 'likes',
       'care_sick', 'fav_food', 'stresses', 'inner_world', 'anxieties',
       'current_stress', 'hopes_wishes', 'know_well', 'friends_social',
       'Aggro_argue', 'Always_never', 'negative_personality',
       'offensive_expressions', 'insult', 'humiliate', 'not_calm',
       'hate_subjects', 'sudden_discussion', 'idk_what's_going_on',
       'calm_breaks', 'argue_then_leave', 'silent_for_calm',
       'good_to_leave_home', 'silence_instead_of_discussion',
       'silence_for_harm', 'silence_fear_anger', 'I'm_right', 'accusations',
       'I'm_not_guilty', 'I'm_not_wrong', 'no_hesitancy_inadequate',
       'you're_inadequate', 'incompetence', 'Divorce_Y_N'],
      dtype='object')

In [8]:
# How many missing zeros are mising in each feature
feature_columns = ['Sorry_end', 'Ignore_diff', 'begin_correct', 'Contact', 'Special_time',
       'No_home_time', '2_strangers', 'enjoy_holiday', 'enjoy_travel',
       'common_goals', 'harmony', 'freeom_value', 'entertain', 'people_goals',
       'dreams', 'love', 'happy', 'marriage', 'roles', 'trust', 'likes',
       'care_sick', 'fav_food', 'stresses', 'inner_world', 'anxieties',
       'current_stress', 'hopes_wishes', 'know_well', 'friends_social',
       'Aggro_argue', 'Always_never', 'negative_personality',
       'offensive_expressions', 'insult', 'humiliate', 'not_calm',
       'hate_subjects', 'sudden_discussion', "idk_what's_going_on",
       'calm_breaks', 'argue_then_leave', 'silent_for_calm',
       'good_to_leave_home', 'silence_instead_of_discussion',
       'silence_for_harm', 'silence_fear_anger', "I'm_right", 'accusations',
       "I'm_not_guilty", "I'm_not_wrong", 'no_hesitancy_inadequate',
       "you're_inadequate", 'incompetence']
for column in feature_columns:
    print("============================================")
    print(f"{column} ==> Missing zeros : {len(df.loc[df[column] == 0])}")

Sorry_end ==> Missing zeros : 69
Ignore_diff ==> Missing zeros : 59
begin_correct ==> Missing zeros : 51
Contact ==> Missing zeros : 75
Special_time ==> Missing zeros : 82
No_home_time ==> Missing zeros : 86
2_strangers ==> Missing zeros : 114
enjoy_holiday ==> Missing zeros : 81
enjoy_travel ==> Missing zeros : 84
common_goals ==> Missing zeros : 62
harmony ==> Missing zeros : 71
freeom_value ==> Missing zeros : 58
entertain ==> Missing zeros : 47
people_goals ==> Missing zeros : 66
dreams ==> Missing zeros : 69
love ==> Missing zeros : 75
happy ==> Missing zeros : 73
marriage ==> Missing zeros : 79
roles ==> Missing zeros : 77
trust ==> Missing zeros : 81
likes ==> Missing zeros : 78
care_sick ==> Missing zeros : 87
fav_food ==> Missing zeros : 90
stresses ==> Missing zeros : 72
inner_world ==> Missing zeros : 63
anxieties ==> Missing zeros : 72
current_stress ==> Missing zeros : 77
hopes_wishes ==> Missing zeros : 85
know_well ==> Missing zeros : 81
friends_social ==> Missing zeros 

In [9]:
from sklearn.impute import SimpleImputer

fill_values = SimpleImputer(missing_values=0, strategy="mean", copy=False)

df[feature_columns] = fill_values.fit_transform(df[feature_columns])

In [10]:
for column in feature_columns:
    print("============================================")
    print(f"{column} ==> Missing zeros : {len(df.loc[df[column] == 0])}")

Sorry_end ==> Missing zeros : 0
Ignore_diff ==> Missing zeros : 0
begin_correct ==> Missing zeros : 0
Contact ==> Missing zeros : 0
Special_time ==> Missing zeros : 0
No_home_time ==> Missing zeros : 0
2_strangers ==> Missing zeros : 0
enjoy_holiday ==> Missing zeros : 0
enjoy_travel ==> Missing zeros : 0
common_goals ==> Missing zeros : 0
harmony ==> Missing zeros : 0
freeom_value ==> Missing zeros : 0
entertain ==> Missing zeros : 0
people_goals ==> Missing zeros : 0
dreams ==> Missing zeros : 0
love ==> Missing zeros : 0
happy ==> Missing zeros : 0
marriage ==> Missing zeros : 0
roles ==> Missing zeros : 0
trust ==> Missing zeros : 0
likes ==> Missing zeros : 0
care_sick ==> Missing zeros : 0
fav_food ==> Missing zeros : 0
stresses ==> Missing zeros : 0
inner_world ==> Missing zeros : 0
anxieties ==> Missing zeros : 0
current_stress ==> Missing zeros : 0
hopes_wishes ==> Missing zeros : 0
know_well ==> Missing zeros : 0
friends_social ==> Missing zeros : 0
Aggro_argue ==> Missing ze

In [11]:
# splitting data arrays into two subsets: for training data and for testing data

from sklearn.model_selection import train_test_split

X = df[feature_columns]
y = df.Divorce_Y_N

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [12]:
# display format

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

def evaluate(model, X_train, X_test, y_train, y_test):
    y_test_pred = model.predict(X_test)
    y_train_pred = model.predict(X_train)

    print("TRAINIG RESULTS: \n===============================")
    clf_report = pd.DataFrame(classification_report(y_train, y_train_pred, output_dict=True))
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y_train, y_train_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y_train, y_train_pred):.4f}")
    print(f"CLASSIFICATION REPORT:\n{clf_report}")

    print("TESTING RESULTS: \n===============================")
    clf_report = pd.DataFrame(classification_report(y_test, y_test_pred, output_dict=True))
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y_test, y_test_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y_test, y_test_pred):.4f}")
    print(f"CLASSIFICATION REPORT:\n{clf_report}")

In [13]:
# Predicting Divorce using Bagging Classifier

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()
bagging_clf = BaggingClassifier(base_estimator=tree, n_estimators=1500, random_state=42)
bagging_clf.fit(X_train, y_train)

evaluate(bagging_clf, X_train, X_test, y_train, y_test)

TRAINIG RESULTS: 
CONFUSION MATRIX:
[[61  0]
 [ 0 58]]
ACCURACY SCORE:
1.0000
CLASSIFICATION REPORT:
              0     1  accuracy  macro avg  weighted avg
precision  1.00  1.00      1.00       1.00          1.00
recall     1.00  1.00      1.00       1.00          1.00
f1-score   1.00  1.00      1.00       1.00          1.00
support   61.00 58.00      1.00     119.00        119.00
TESTING RESULTS: 
CONFUSION MATRIX:
[[24  1]
 [ 1 25]]
ACCURACY SCORE:
0.9608
CLASSIFICATION REPORT:
              0     1  accuracy  macro avg  weighted avg
precision  0.96  0.96      0.96       0.96          0.96
recall     0.96  0.96      0.96       0.96          0.96
f1-score   0.96  0.96      0.96       0.96          0.96
support   25.00 26.00      0.96      51.00         51.00


In [14]:
scores = {
    'Bagging Classifier': {
        'Train': accuracy_score(y_train, bagging_clf.predict(X_train)),
        'Test': accuracy_score(y_test, bagging_clf.predict(X_test)),
    },
}

In [15]:
# Predicting Divorce using RandomForest Classifier

from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=42, n_estimators=1000)
rf_clf.fit(X_train, y_train)
evaluate(rf_clf, X_train, X_test, y_train, y_test)

TRAINIG RESULTS: 
CONFUSION MATRIX:
[[61  0]
 [ 0 58]]
ACCURACY SCORE:
1.0000
CLASSIFICATION REPORT:
              0     1  accuracy  macro avg  weighted avg
precision  1.00  1.00      1.00       1.00          1.00
recall     1.00  1.00      1.00       1.00          1.00
f1-score   1.00  1.00      1.00       1.00          1.00
support   61.00 58.00      1.00     119.00        119.00
TESTING RESULTS: 
CONFUSION MATRIX:
[[25  0]
 [ 1 25]]
ACCURACY SCORE:
0.9804
CLASSIFICATION REPORT:
              0     1  accuracy  macro avg  weighted avg
precision  0.96  1.00      0.98       0.98          0.98
recall     1.00  0.96      0.98       0.98          0.98
f1-score   0.98  0.98      0.98       0.98          0.98
support   25.00 26.00      0.98      51.00         51.00


In [16]:
scores['Random Forest'] = {
        'Train': accuracy_score(y_train, rf_clf.predict(X_train)),
        'Test': accuracy_score(y_test, rf_clf.predict(X_test)),
    }

In [17]:
# Predicting Divorce using ExtraTrees Classifier

from sklearn.ensemble import ExtraTreesClassifier

ex_tree_clf = ExtraTreesClassifier(n_estimators=1000, max_features=7, random_state=42)
ex_tree_clf.fit(X_train, y_train)
evaluate(ex_tree_clf, X_train, X_test, y_train, y_test)

TRAINIG RESULTS: 
CONFUSION MATRIX:
[[61  0]
 [ 0 58]]
ACCURACY SCORE:
1.0000
CLASSIFICATION REPORT:
              0     1  accuracy  macro avg  weighted avg
precision  1.00  1.00      1.00       1.00          1.00
recall     1.00  1.00      1.00       1.00          1.00
f1-score   1.00  1.00      1.00       1.00          1.00
support   61.00 58.00      1.00     119.00        119.00
TESTING RESULTS: 
CONFUSION MATRIX:
[[25  0]
 [ 1 25]]
ACCURACY SCORE:
0.9804
CLASSIFICATION REPORT:
              0     1  accuracy  macro avg  weighted avg
precision  0.96  1.00      0.98       0.98          0.98
recall     1.00  0.96      0.98       0.98          0.98
f1-score   0.98  0.98      0.98       0.98          0.98
support   25.00 26.00      0.98      51.00         51.00


In [18]:
# Create the model for the website
import joblib
joblib.dump(rf_clf, "website/rf_clf_bagging2.pkl")

['website/rf_clf_bagging2.pkl']